---

config_version: 1.0

#===================================#
setup: false
th: false
#======Settings Get Post============#
day: 1
hour: 0
minute: 0
#=============Countries==============#
countries: 
#====User Pass web.postman.co========#
user:
pass: 
#=========Bordcast Message==========#
brodcast_message:
bordcast_type:
#========== UI Inferface ===========#
#{covidstatus} = Show Covid Total\n {color} = Random Color \n{newcase} = New Case \n {newdeath} = New Death\n{newrecovered] = New Recovered\n {totaldeath} = Total Death \n{totalrecoverd} = TotalRecoverd"
title: §a-=- §eCovidStatus §a
content: §aTotal: {covidstatus}
btn: Exit
btn-img-type: 0
btn-img: textures/items/barrier.png
#===================================#

...
